# Generated by Django 4.2.27 on 2026-01-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGradeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.IntegerField(help_text='AI tavsiya etgan ball')),
                ('max_score', models.IntegerField(help_text='Maksimal ball')),
                ('confidence', models.FloatField(default=0.0, help_text='AI ishonch darajasi (0-1)')),
                ('analysis', models.TextField(help_text='AI tahlili va izohlar')),
                ('strengths', models.TextField(blank=True, help_text='Kuchli tomonlar')),
                ('weaknesses', models.TextField(blank=True, help_text='Zaif tomonlar')),
                ('suggestions', models.TextField(blank=True, help_text="Yaxshilash bo'yicha takliflar")),
                ('teacher_score', models.IntegerField(blank=True, help_text="O'qituvchi qo'ygan ball", null=True)),
                ('teacher_feedback', models.TextField(blank=True, help_text="O'qituvchi izohi")),
                ('score_difference', models.IntegerField(default=0, help_text="AI va o'qituvchi baho farqi")),
                ('is_reviewed', models.BooleanField(default=False, help_text="O'qituvchi ko'rib chiqdi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation', to='courses.submission')),
            ],
            options={
                'verbose_name': 'AI Baho Tavsiyasi',
                'verbose_name_plural': 'AI Baho Tavsiялari',
                'ordering': ['-created_at'],
            },
        ),
    ]
