# Generated by Django 6.0.2 on 2026-02-16 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_thumbnail_alter_question_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='easy', max_length=20)),
                ('initial_code', models.TextField(blank=True)),
                ('solution', models.TextField()),
                ('test_cases', models.JSONField(default=list)),
                ('time_limit', models.PositiveIntegerField(default=300)),
                ('xp_reward', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kod masala',
                'verbose_name_plural': 'Kod masalalar',
            },
        ),
        migrations.CreateModel(
            name='TypingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='easy', max_length=20)),
                ('language', models.CharField(default='uz', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Typing matn',
                'verbose_name_plural': 'Typing matnlar',
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('typing', 'Tez yozish'), ('code', 'Kod yozish'), ('math', 'Matematik'), ('memory', 'Xotira')], max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'yin natijasi",
                'verbose_name_plural': "O'yin natijalari",
                'ordering': ['-played_at'],
            },
        ),
    ]
