# Generated by Django 6.0.2 on 2026-02-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_codechallenge_typingtext_gamescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('match', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Dasturlash'), ('python', 'Python'), ('web', 'Veb'), ('database', "Ma'lumotlar bazasi"), ('general', 'Umumiy IT')], default='programming', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Memory karta',
                'verbose_name_plural': 'Memory kartalar',
            },
        ),
    ]
